travis:
  secure:
    BINSTAR_TOKEN: Vu7TmZCyoH1rhxpIlYoLIALuqIegpXO6x0pafT7eFXQ729fa99X0sY4HDwnEMGhYT+nFswrqt4jCL+lvmg9GPW5zfk7Y5RnXYv0xAlggqqMv2q/C4cJl4hJRJMdk717pr0OMDgj8kFWcoJQC7nUxD3VWyVR5gEGsHNsPzL8NxNzegSUspt1+Ky1rtCW2OV3lJCJmfWLbVobNY3ALwtSGkbFjNCdC7aHpue+F793VP2d147rRhR4uDKUqC/AY++y6ndS0DGDPfUmqAy/lEIaeE9qVcIi7E0K6mWHpUtZ3dwrMvsD3RFHWmlVRrhk8dDPwv9TbWqvoT//F9grexLIGmalgNuLriKr4RN69yoP6gEyMCdwYBQc+eNsCLI3+XD/C1BCNaEfSjo/0vxL3U9msgHDHyJMimqRlIduUazZTGjkrmBKQP5cYTLNe2LKUkaLXkte1v3PYj2B2AnSBZCW7p3Bg45uq6ZnrJGP9cfaYbcGshBN+sLpO1EJeuHEaV8d+mgZXao3IDbSa066IGwzQOf9sf3J9dqlu3F72sV0b0FnVaKym2jIgufAg8JmLHhKsK9D6sRFqkctuk3mFdJ2vjf6vj0gOf5HyPDONBz2/dG0EezsSjL6iR3j8BjkqOm1hZq29ahEyZfPBn/PSyEx2CfztFS9pVmNNB8PyYVWMIt0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
