travis:
  secure:
    BINSTAR_TOKEN: mklonPpcs7M+iO34sFuf43puaMW+bmRLMdwSZN+nfDyKrgmezanj/IKP030cp+da2EN2IwnKifYR6GOsCPCY5UZP6xSXVoHua/AqrZ65HT/3COJHOybBpDucpXSycz62ssWoiVmMokwxud/KAN+Bb7zUNbLtkrqpVDBhnsNHymhYlTP60C/T73hV1Xj8nJGpG40BAbHVMs4Fj7n6rYvjyK9wMcoHlQUvb4IfyuwI7Ag5JGQLNZMmqW7x0peDGBsqwcY/uDnBqjIMc43LnA8xNVKbOIm06rKj9xMLAFWtEYg4YaeuJcezfUqKuvr4ZTtye+1C1yYKNUkSlJ7yp+hIje1unaGS2AaWABTDrwCaV0/T/wVYX5Nlk4OiswFg52YHpc9JlQXnqwCVvXIuoAhYZ43ZOVFpHW+if9eDvY4mgLGDYqZCzOh8rcsbg+LNPXCPOlpx5VPwTIh+43hq/guAkFLoB28bSLx1dGJ1bXJMR+xhfgFtjmY7GBOrw95IMKvNYuEOPLkJ6+KFKcPStSQqhc3wzkufLuNY++NpSVYIfOwJ8s442OU+GqzcXNDBYwEwr3IIJpQ14Qij7ezAXkiNhPGLS0PX5zVNzsve44lcCejXQawiOlxIdtUNaALnTDw0pMGKNf+0Her+HMOihRlJdGkVwucxts2pml3fDFLeTfs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
